// AUTO-GENERATED by scripts/migrate-wiki.mjs from the wiki _Sidebar.md.
// Do not hand-edit — re-run `npm run migrate` instead.
export const sidebar = [
  {
    "text": "Getting started",
    "collapsed": false,
    "items": [
      {
        "text": "Quickstart: Rust",
        "link": "/Quickstart-Rust"
      },
      {
        "text": "Quickstart: Python",
        "link": "/Quickstart-Python"
      },
      {
        "text": "Quickstart: Node",
        "link": "/Quickstart-Node"
      },
      {
        "text": "Quickstart: WASM",
        "link": "/Quickstart-WASM"
      }
    ]
  },
  {
    "text": "Reference",
    "collapsed": false,
    "items": [
      {
        "text": "Indicators overview",
        "link": "/Indicators-Overview"
      },
      {
        "text": "Warmup periods",
        "link": "/Warmup-Periods"
      },
      {
        "text": "Streaming vs batch",
        "link": "/Streaming-vs-Batch"
      },
      {
        "text": "Indicator chaining",
        "link": "/Indicator-Chaining"
      },
      {
        "text": "Data layer",
        "link": "/Data-Layer"
      }
    ]
  },
  {
    "text": "Guides",
    "collapsed": false,
    "items": [
      {
        "text": "Cookbook",
        "link": "/Cookbook"
      },
      {
        "text": "TA-Lib migration",
        "link": "/TA-Lib-Migration"
      },
      {
        "text": "FAQ",
        "link": "/FAQ"
      }
    ]
  },
  {
    "text": "Moving Averages",
    "collapsed": true,
    "items": [
      {
        "text": "Alligator",
        "link": "/Indicator-Alligator"
      },
      {
        "text": "Alma",
        "link": "/Indicator-Alma"
      },
      {
        "text": "Dema",
        "link": "/Indicator-Dema"
      },
      {
        "text": "Ema",
        "link": "/Indicator-Ema"
      },
      {
        "text": "Evwma",
        "link": "/Indicator-Evwma"
      },
      {
        "text": "Frama",
        "link": "/Indicator-Frama"
      },
      {
        "text": "Hma",
        "link": "/Indicator-Hma"
      },
      {
        "text": "Jma",
        "link": "/Indicator-Jma"
      },
      {
        "text": "Kama",
        "link": "/Indicator-Kama"
      },
      {
        "text": "McGinleyDynamic",
        "link": "/Indicator-McGinleyDynamic"
      },
      {
        "text": "Sma",
        "link": "/Indicator-Sma"
      },
      {
        "text": "Smma",
        "link": "/Indicator-Smma"
      },
      {
        "text": "T3",
        "link": "/Indicator-T3"
      },
      {
        "text": "Tema",
        "link": "/Indicator-Tema"
      },
      {
        "text": "Trima",
        "link": "/Indicator-Trima"
      },
      {
        "text": "Vidya",
        "link": "/Indicator-Vidya"
      },
      {
        "text": "Vwma",
        "link": "/Indicator-Vwma"
      },
      {
        "text": "Wma",
        "link": "/Indicator-Wma"
      },
      {
        "text": "Zlema",
        "link": "/Indicator-Zlema"
      }
    ]
  },
  {
    "text": "Momentum Oscillators",
    "collapsed": true,
    "items": [
      {
        "text": "AnchoredRsi",
        "link": "/Indicator-AnchoredRsi"
      },
      {
        "text": "AwesomeOscillator",
        "link": "/Indicator-AwesomeOscillator"
      },
      {
        "text": "Cci",
        "link": "/Indicator-Cci"
      },
      {
        "text": "Cmo",
        "link": "/Indicator-Cmo"
      },
      {
        "text": "ConnorsRsi",
        "link": "/Indicator-ConnorsRsi"
      },
      {
        "text": "Inertia",
        "link": "/Indicator-Inertia"
      },
      {
        "text": "Kst",
        "link": "/Indicator-Kst"
      },
      {
        "text": "LaguerreRsi",
        "link": "/Indicator-LaguerreRsi"
      },
      {
        "text": "Mfi",
        "link": "/Indicator-Mfi"
      },
      {
        "text": "Mom",
        "link": "/Indicator-Mom"
      },
      {
        "text": "Pgo",
        "link": "/Indicator-Pgo"
      },
      {
        "text": "Pmo",
        "link": "/Indicator-Pmo"
      },
      {
        "text": "Roc",
        "link": "/Indicator-Roc"
      },
      {
        "text": "Rocp",
        "link": "/Indicator-Rocp"
      },
      {
        "text": "Rocr",
        "link": "/Indicator-Rocr"
      },
      {
        "text": "Rocr100",
        "link": "/Indicator-Rocr100"
      },
      {
        "text": "Rsi",
        "link": "/Indicator-Rsi"
      },
      {
        "text": "Rvi",
        "link": "/Indicator-Rvi"
      },
      {
        "text": "Smi",
        "link": "/Indicator-Smi"
      },
      {
        "text": "Stochastic",
        "link": "/Indicator-Stochastic"
      },
      {
        "text": "StochRsi",
        "link": "/Indicator-StochRsi"
      },
      {
        "text": "Tsi",
        "link": "/Indicator-Tsi"
      },
      {
        "text": "UltimateOscillator",
        "link": "/Indicator-UltimateOscillator"
      },
      {
        "text": "WilliamsR",
        "link": "/Indicator-WilliamsR"
      }
    ]
  },
  {
    "text": "Trend & Directional",
    "collapsed": true,
    "items": [
      {
        "text": "Adx",
        "link": "/Indicator-Adx"
      },
      {
        "text": "Adxr",
        "link": "/Indicator-Adxr"
      },
      {
        "text": "Aroon",
        "link": "/Indicator-Aroon"
      },
      {
        "text": "AroonOscillator",
        "link": "/Indicator-AroonOscillator"
      },
      {
        "text": "ChoppinessIndex",
        "link": "/Indicator-ChoppinessIndex"
      },
      {
        "text": "Dx",
        "link": "/Indicator-Dx"
      },
      {
        "text": "MacdExt",
        "link": "/Indicator-MacdExt"
      },
      {
        "text": "MacdFix",
        "link": "/Indicator-MacdFix"
      },
      {
        "text": "MacdIndicator",
        "link": "/Indicator-MacdIndicator"
      },
      {
        "text": "MassIndex",
        "link": "/Indicator-MassIndex"
      },
      {
        "text": "MinusDi",
        "link": "/Indicator-MinusDi"
      },
      {
        "text": "MinusDm",
        "link": "/Indicator-MinusDm"
      },
      {
        "text": "PlusDi",
        "link": "/Indicator-PlusDi"
      },
      {
        "text": "PlusDm",
        "link": "/Indicator-PlusDm"
      },
      {
        "text": "Rwi",
        "link": "/Indicator-Rwi"
      },
      {
        "text": "Tii",
        "link": "/Indicator-Tii"
      },
      {
        "text": "Trix",
        "link": "/Indicator-Trix"
      },
      {
        "text": "VerticalHorizontalFilter",
        "link": "/Indicator-VerticalHorizontalFilter"
      },
      {
        "text": "Vortex",
        "link": "/Indicator-Vortex"
      },
      {
        "text": "WaveTrend",
        "link": "/Indicator-WaveTrend"
      }
    ]
  },
  {
    "text": "Price Oscillators",
    "collapsed": true,
    "items": [
      {
        "text": "AcceleratorOscillator",
        "link": "/Indicator-AcceleratorOscillator"
      },
      {
        "text": "Apo",
        "link": "/Indicator-Apo"
      },
      {
        "text": "AwesomeOscillatorHistogram",
        "link": "/Indicator-AwesomeOscillatorHistogram"
      },
      {
        "text": "BalanceOfPower",
        "link": "/Indicator-BalanceOfPower"
      },
      {
        "text": "Cfo",
        "link": "/Indicator-Cfo"
      },
      {
        "text": "Coppock",
        "link": "/Indicator-Coppock"
      },
      {
        "text": "Dpo",
        "link": "/Indicator-Dpo"
      },
      {
        "text": "ElderImpulse",
        "link": "/Indicator-ElderImpulse"
      },
      {
        "text": "Ppo",
        "link": "/Indicator-Ppo"
      },
      {
        "text": "Stc",
        "link": "/Indicator-Stc"
      },
      {
        "text": "ZeroLagMacd",
        "link": "/Indicator-ZeroLagMacd"
      }
    ]
  },
  {
    "text": "Volatility & Bands",
    "collapsed": true,
    "items": [
      {
        "text": "Atr",
        "link": "/Indicator-Atr"
      },
      {
        "text": "BollingerBands",
        "link": "/Indicator-BollingerBands"
      },
      {
        "text": "BollingerBandwidth",
        "link": "/Indicator-BollingerBandwidth"
      },
      {
        "text": "ChaikinVolatility",
        "link": "/Indicator-ChaikinVolatility"
      },
      {
        "text": "DetrendedStdDev",
        "link": "/Indicator-DetrendedStdDev"
      },
      {
        "text": "Donchian",
        "link": "/Indicator-Donchian"
      },
      {
        "text": "GarmanKlassVolatility",
        "link": "/Indicator-GarmanKlassVolatility"
      },
      {
        "text": "HistoricalVolatility",
        "link": "/Indicator-HistoricalVolatility"
      },
      {
        "text": "Keltner",
        "link": "/Indicator-Keltner"
      },
      {
        "text": "Natr",
        "link": "/Indicator-Natr"
      },
      {
        "text": "ParkinsonVolatility",
        "link": "/Indicator-ParkinsonVolatility"
      },
      {
        "text": "PercentB",
        "link": "/Indicator-PercentB"
      },
      {
        "text": "RogersSatchellVolatility",
        "link": "/Indicator-RogersSatchellVolatility"
      },
      {
        "text": "RviVolatility",
        "link": "/Indicator-RviVolatility"
      },
      {
        "text": "StdDev",
        "link": "/Indicator-StdDev"
      },
      {
        "text": "TrueRange",
        "link": "/Indicator-TrueRange"
      },
      {
        "text": "UlcerIndex",
        "link": "/Indicator-UlcerIndex"
      },
      {
        "text": "YangZhangVolatility",
        "link": "/Indicator-YangZhangVolatility"
      }
    ]
  },
  {
    "text": "Bands & Channels",
    "collapsed": true,
    "items": [
      {
        "text": "AccelerationBands",
        "link": "/Indicator-AccelerationBands"
      },
      {
        "text": "AtrBands",
        "link": "/Indicator-AtrBands"
      },
      {
        "text": "DoubleBollinger",
        "link": "/Indicator-DoubleBollinger"
      },
      {
        "text": "FractalChaosBands",
        "link": "/Indicator-FractalChaosBands"
      },
      {
        "text": "HurstChannel",
        "link": "/Indicator-HurstChannel"
      },
      {
        "text": "LinRegChannel",
        "link": "/Indicator-LinRegChannel"
      },
      {
        "text": "MaEnvelope",
        "link": "/Indicator-MaEnvelope"
      },
      {
        "text": "StandardErrorBands",
        "link": "/Indicator-StandardErrorBands"
      },
      {
        "text": "StarcBands",
        "link": "/Indicator-StarcBands"
      },
      {
        "text": "TtmSqueeze",
        "link": "/Indicator-TtmSqueeze"
      },
      {
        "text": "VwapStdDevBands",
        "link": "/Indicator-VwapStdDevBands"
      }
    ]
  },
  {
    "text": "Trailing Stops",
    "collapsed": true,
    "items": [
      {
        "text": "AtrTrailingStop",
        "link": "/Indicator-AtrTrailingStop"
      },
      {
        "text": "ChandeKrollStop",
        "link": "/Indicator-ChandeKrollStop"
      },
      {
        "text": "ChandelierExit",
        "link": "/Indicator-ChandelierExit"
      },
      {
        "text": "DonchianStop",
        "link": "/Indicator-DonchianStop"
      },
      {
        "text": "HiLoActivator",
        "link": "/Indicator-HiLoActivator"
      },
      {
        "text": "PercentageTrailingStop",
        "link": "/Indicator-PercentageTrailingStop"
      },
      {
        "text": "Psar",
        "link": "/Indicator-Psar"
      },
      {
        "text": "RenkoTrailingStop",
        "link": "/Indicator-RenkoTrailingStop"
      },
      {
        "text": "SarExt",
        "link": "/Indicator-SarExt"
      },
      {
        "text": "StepTrailingStop",
        "link": "/Indicator-StepTrailingStop"
      },
      {
        "text": "SuperTrend",
        "link": "/Indicator-SuperTrend"
      },
      {
        "text": "VoltyStop",
        "link": "/Indicator-VoltyStop"
      },
      {
        "text": "YoyoExit",
        "link": "/Indicator-YoyoExit"
      }
    ]
  },
  {
    "text": "Volume",
    "collapsed": true,
    "items": [
      {
        "text": "AdOscillator",
        "link": "/Indicator-AdOscillator"
      },
      {
        "text": "Adl",
        "link": "/Indicator-Adl"
      },
      {
        "text": "AnchoredVwap",
        "link": "/Indicator-AnchoredVwap"
      },
      {
        "text": "ChaikinMoneyFlow",
        "link": "/Indicator-ChaikinMoneyFlow"
      },
      {
        "text": "ChaikinOscillator",
        "link": "/Indicator-ChaikinOscillator"
      },
      {
        "text": "DemandIndex",
        "link": "/Indicator-DemandIndex"
      },
      {
        "text": "EaseOfMovement",
        "link": "/Indicator-EaseOfMovement"
      },
      {
        "text": "ForceIndex",
        "link": "/Indicator-ForceIndex"
      },
      {
        "text": "Kvo",
        "link": "/Indicator-Kvo"
      },
      {
        "text": "MarketFacilitationIndex",
        "link": "/Indicator-MarketFacilitationIndex"
      },
      {
        "text": "Nvi",
        "link": "/Indicator-Nvi"
      },
      {
        "text": "Obv",
        "link": "/Indicator-Obv"
      },
      {
        "text": "Pvi",
        "link": "/Indicator-Pvi"
      },
      {
        "text": "RollingVwap",
        "link": "/Indicator-RollingVwap"
      },
      {
        "text": "Tsv",
        "link": "/Indicator-Tsv"
      },
      {
        "text": "VolumeOscillator",
        "link": "/Indicator-VolumeOscillator"
      },
      {
        "text": "VolumePriceTrend",
        "link": "/Indicator-VolumePriceTrend"
      },
      {
        "text": "Vwap",
        "link": "/Indicator-Vwap"
      },
      {
        "text": "Vzo",
        "link": "/Indicator-Vzo"
      }
    ]
  },
  {
    "text": "Price Statistics",
    "collapsed": true,
    "items": [
      {
        "text": "Autocorrelation",
        "link": "/Indicator-Autocorrelation"
      },
      {
        "text": "AvgPrice",
        "link": "/Indicator-AvgPrice"
      },
      {
        "text": "Beta",
        "link": "/Indicator-Beta"
      },
      {
        "text": "CoefficientOfVariation",
        "link": "/Indicator-CoefficientOfVariation"
      },
      {
        "text": "Cointegration",
        "link": "/Indicator-Cointegration"
      },
      {
        "text": "HurstExponent",
        "link": "/Indicator-HurstExponent"
      },
      {
        "text": "Kurtosis",
        "link": "/Indicator-Kurtosis"
      },
      {
        "text": "LeadLagCrossCorrelation",
        "link": "/Indicator-LeadLagCrossCorrelation"
      },
      {
        "text": "LinearRegression",
        "link": "/Indicator-LinearRegression"
      },
      {
        "text": "LinRegAngle",
        "link": "/Indicator-LinRegAngle"
      },
      {
        "text": "LinRegIntercept",
        "link": "/Indicator-LinRegIntercept"
      },
      {
        "text": "LinRegSlope",
        "link": "/Indicator-LinRegSlope"
      },
      {
        "text": "MedianAbsoluteDeviation",
        "link": "/Indicator-MedianAbsoluteDeviation"
      },
      {
        "text": "MedianPrice",
        "link": "/Indicator-MedianPrice"
      },
      {
        "text": "MidPoint",
        "link": "/Indicator-MidPoint"
      },
      {
        "text": "MidPrice",
        "link": "/Indicator-MidPrice"
      },
      {
        "text": "PairSpreadZScore",
        "link": "/Indicator-PairSpreadZScore"
      },
      {
        "text": "PairwiseBeta",
        "link": "/Indicator-PairwiseBeta"
      },
      {
        "text": "PearsonCorrelation",
        "link": "/Indicator-PearsonCorrelation"
      },
      {
        "text": "RelativeStrengthAB",
        "link": "/Indicator-RelativeStrengthAB"
      },
      {
        "text": "RSquared",
        "link": "/Indicator-RSquared"
      },
      {
        "text": "Skewness",
        "link": "/Indicator-Skewness"
      },
      {
        "text": "SpearmanCorrelation",
        "link": "/Indicator-SpearmanCorrelation"
      },
      {
        "text": "StandardError",
        "link": "/Indicator-StandardError"
      },
      {
        "text": "Tsf",
        "link": "/Indicator-Tsf"
      },
      {
        "text": "TypicalPrice",
        "link": "/Indicator-TypicalPrice"
      },
      {
        "text": "Variance",
        "link": "/Indicator-Variance"
      },
      {
        "text": "WeightedClose",
        "link": "/Indicator-WeightedClose"
      },
      {
        "text": "ZScore",
        "link": "/Indicator-ZScore"
      }
    ]
  },
  {
    "text": "Market Profile",
    "collapsed": true,
    "items": [
      {
        "text": "InitialBalance",
        "link": "/Indicator-InitialBalance"
      },
      {
        "text": "OpeningRange",
        "link": "/Indicator-OpeningRange"
      },
      {
        "text": "TpoProfile",
        "link": "/Indicator-TpoProfile"
      },
      {
        "text": "ValueArea",
        "link": "/Indicator-ValueArea"
      },
      {
        "text": "VolumeProfile",
        "link": "/Indicator-VolumeProfile"
      }
    ]
  },
  {
    "text": "Ichimoku & Charts",
    "collapsed": true,
    "items": [
      {
        "text": "HeikinAshi",
        "link": "/Indicator-HeikinAshi"
      },
      {
        "text": "Ichimoku",
        "link": "/Indicator-Ichimoku"
      }
    ]
  },
  {
    "text": "Pivots & S/R",
    "collapsed": true,
    "items": [
      {
        "text": "Camarilla",
        "link": "/Indicator-Camarilla"
      },
      {
        "text": "ClassicPivots",
        "link": "/Indicator-ClassicPivots"
      },
      {
        "text": "DemarkPivots",
        "link": "/Indicator-DemarkPivots"
      },
      {
        "text": "FibonacciPivots",
        "link": "/Indicator-FibonacciPivots"
      },
      {
        "text": "WilliamsFractals",
        "link": "/Indicator-WilliamsFractals"
      },
      {
        "text": "WoodiePivots",
        "link": "/Indicator-WoodiePivots"
      },
      {
        "text": "ZigZag",
        "link": "/Indicator-ZigZag"
      }
    ]
  },
  {
    "text": "DeMark",
    "collapsed": true,
    "items": [
      {
        "text": "TdCombo",
        "link": "/Indicator-TdCombo"
      },
      {
        "text": "TdCountdown",
        "link": "/Indicator-TdCountdown"
      },
      {
        "text": "TdDeMarker",
        "link": "/Indicator-TdDeMarker"
      },
      {
        "text": "TdDifferential",
        "link": "/Indicator-TdDifferential"
      },
      {
        "text": "TdLines",
        "link": "/Indicator-TdLines"
      },
      {
        "text": "TdOpen",
        "link": "/Indicator-TdOpen"
      },
      {
        "text": "TdPressure",
        "link": "/Indicator-TdPressure"
      },
      {
        "text": "TdRangeProjection",
        "link": "/Indicator-TdRangeProjection"
      },
      {
        "text": "TdRei",
        "link": "/Indicator-TdRei"
      },
      {
        "text": "TdRiskLevel",
        "link": "/Indicator-TdRiskLevel"
      },
      {
        "text": "TdSequential",
        "link": "/Indicator-TdSequential"
      },
      {
        "text": "TdSetup",
        "link": "/Indicator-TdSetup"
      }
    ]
  },
  {
    "text": "Candlestick Patterns",
    "collapsed": true,
    "items": [
      {
        "text": "AbandonedBaby",
        "link": "/Indicator-AbandonedBaby"
      },
      {
        "text": "AdvanceBlock",
        "link": "/Indicator-AdvanceBlock"
      },
      {
        "text": "BeltHold",
        "link": "/Indicator-BeltHold"
      },
      {
        "text": "Breakaway",
        "link": "/Indicator-Breakaway"
      },
      {
        "text": "ClosingMarubozu",
        "link": "/Indicator-ClosingMarubozu"
      },
      {
        "text": "ConcealingBabySwallow",
        "link": "/Indicator-ConcealingBabySwallow"
      },
      {
        "text": "Counterattack",
        "link": "/Indicator-Counterattack"
      },
      {
        "text": "Doji",
        "link": "/Indicator-Doji"
      },
      {
        "text": "DojiStar",
        "link": "/Indicator-DojiStar"
      },
      {
        "text": "DownsideGapThreeMethods",
        "link": "/Indicator-DownsideGapThreeMethods"
      },
      {
        "text": "DragonflyDoji",
        "link": "/Indicator-DragonflyDoji"
      },
      {
        "text": "Engulfing",
        "link": "/Indicator-Engulfing"
      },
      {
        "text": "EveningDojiStar",
        "link": "/Indicator-EveningDojiStar"
      },
      {
        "text": "FallingThreeMethods",
        "link": "/Indicator-FallingThreeMethods"
      },
      {
        "text": "GapSideBySideWhite",
        "link": "/Indicator-GapSideBySideWhite"
      },
      {
        "text": "GravestoneDoji",
        "link": "/Indicator-GravestoneDoji"
      },
      {
        "text": "Hammer",
        "link": "/Indicator-Hammer"
      },
      {
        "text": "HangingMan",
        "link": "/Indicator-HangingMan"
      },
      {
        "text": "Harami",
        "link": "/Indicator-Harami"
      },
      {
        "text": "HighWave",
        "link": "/Indicator-HighWave"
      },
      {
        "text": "Hikkake",
        "link": "/Indicator-Hikkake"
      },
      {
        "text": "HikkakeModified",
        "link": "/Indicator-HikkakeModified"
      },
      {
        "text": "HomingPigeon",
        "link": "/Indicator-HomingPigeon"
      },
      {
        "text": "IdenticalThreeCrows",
        "link": "/Indicator-IdenticalThreeCrows"
      },
      {
        "text": "InNeck",
        "link": "/Indicator-InNeck"
      },
      {
        "text": "InvertedHammer",
        "link": "/Indicator-InvertedHammer"
      },
      {
        "text": "Kicking",
        "link": "/Indicator-Kicking"
      },
      {
        "text": "KickingByLength",
        "link": "/Indicator-KickingByLength"
      },
      {
        "text": "LadderBottom",
        "link": "/Indicator-LadderBottom"
      },
      {
        "text": "LongLeggedDoji",
        "link": "/Indicator-LongLeggedDoji"
      },
      {
        "text": "LongLine",
        "link": "/Indicator-LongLine"
      },
      {
        "text": "Marubozu",
        "link": "/Indicator-Marubozu"
      },
      {
        "text": "MatchingLow",
        "link": "/Indicator-MatchingLow"
      },
      {
        "text": "MatHold",
        "link": "/Indicator-MatHold"
      },
      {
        "text": "MorningDojiStar",
        "link": "/Indicator-MorningDojiStar"
      },
      {
        "text": "MorningEveningStar",
        "link": "/Indicator-MorningEveningStar"
      },
      {
        "text": "OnNeck",
        "link": "/Indicator-OnNeck"
      },
      {
        "text": "OpeningMarubozu",
        "link": "/Indicator-OpeningMarubozu"
      },
      {
        "text": "PiercingDarkCloud",
        "link": "/Indicator-PiercingDarkCloud"
      },
      {
        "text": "RickshawMan",
        "link": "/Indicator-RickshawMan"
      },
      {
        "text": "RisingThreeMethods",
        "link": "/Indicator-RisingThreeMethods"
      },
      {
        "text": "SeparatingLines",
        "link": "/Indicator-SeparatingLines"
      },
      {
        "text": "ShootingStar",
        "link": "/Indicator-ShootingStar"
      },
      {
        "text": "ShortLine",
        "link": "/Indicator-ShortLine"
      },
      {
        "text": "SpinningTop",
        "link": "/Indicator-SpinningTop"
      },
      {
        "text": "StalledPattern",
        "link": "/Indicator-StalledPattern"
      },
      {
        "text": "StickSandwich",
        "link": "/Indicator-StickSandwich"
      },
      {
        "text": "Takuri",
        "link": "/Indicator-Takuri"
      },
      {
        "text": "TasukiGap",
        "link": "/Indicator-TasukiGap"
      },
      {
        "text": "ThreeInside",
        "link": "/Indicator-ThreeInside"
      },
      {
        "text": "ThreeLineStrike",
        "link": "/Indicator-ThreeLineStrike"
      },
      {
        "text": "ThreeOutside",
        "link": "/Indicator-ThreeOutside"
      },
      {
        "text": "ThreeSoldiersOrCrows",
        "link": "/Indicator-ThreeSoldiersOrCrows"
      },
      {
        "text": "ThreeStarsInSouth",
        "link": "/Indicator-ThreeStarsInSouth"
      },
      {
        "text": "Thrusting",
        "link": "/Indicator-Thrusting"
      },
      {
        "text": "Tweezer",
        "link": "/Indicator-Tweezer"
      },
      {
        "text": "TwoCrows",
        "link": "/Indicator-TwoCrows"
      },
      {
        "text": "UniqueThreeRiver",
        "link": "/Indicator-UniqueThreeRiver"
      },
      {
        "text": "UpsideGapThreeMethods",
        "link": "/Indicator-UpsideGapThreeMethods"
      },
      {
        "text": "UpsideGapTwoCrows",
        "link": "/Indicator-UpsideGapTwoCrows"
      }
    ]
  },
  {
    "text": "Ehlers / Cycle (DSP)",
    "collapsed": true,
    "items": [
      {
        "text": "AdaptiveCycle",
        "link": "/Indicator-AdaptiveCycle"
      },
      {
        "text": "CenterOfGravity",
        "link": "/Indicator-CenterOfGravity"
      },
      {
        "text": "CyberneticCycle",
        "link": "/Indicator-CyberneticCycle"
      },
      {
        "text": "Decycler",
        "link": "/Indicator-Decycler"
      },
      {
        "text": "DecyclerOscillator",
        "link": "/Indicator-DecyclerOscillator"
      },
      {
        "text": "EhlersStochastic",
        "link": "/Indicator-EhlersStochastic"
      },
      {
        "text": "EmpiricalModeDecomposition",
        "link": "/Indicator-EmpiricalModeDecomposition"
      },
      {
        "text": "Fama",
        "link": "/Indicator-Fama"
      },
      {
        "text": "FisherTransform",
        "link": "/Indicator-FisherTransform"
      },
      {
        "text": "HilbertDominantCycle",
        "link": "/Indicator-HilbertDominantCycle"
      },
      {
        "text": "HtDcPhase",
        "link": "/Indicator-HtDcPhase"
      },
      {
        "text": "HtPhasor",
        "link": "/Indicator-HtPhasor"
      },
      {
        "text": "HtTrendMode",
        "link": "/Indicator-HtTrendMode"
      },
      {
        "text": "InstantaneousTrendline",
        "link": "/Indicator-InstantaneousTrendline"
      },
      {
        "text": "InverseFisherTransform",
        "link": "/Indicator-InverseFisherTransform"
      },
      {
        "text": "Mama",
        "link": "/Indicator-Mama"
      },
      {
        "text": "RoofingFilter",
        "link": "/Indicator-RoofingFilter"
      },
      {
        "text": "SineWave",
        "link": "/Indicator-SineWave"
      },
      {
        "text": "SuperSmoother",
        "link": "/Indicator-SuperSmoother"
      }
    ]
  },
  {
    "text": "Risk / Performance",
    "collapsed": true,
    "items": [
      {
        "text": "Alpha",
        "link": "/Indicator-Alpha"
      },
      {
        "text": "AverageDrawdown",
        "link": "/Indicator-AverageDrawdown"
      },
      {
        "text": "CalmarRatio",
        "link": "/Indicator-CalmarRatio"
      },
      {
        "text": "ConditionalValueAtRisk",
        "link": "/Indicator-ConditionalValueAtRisk"
      },
      {
        "text": "DrawdownDuration",
        "link": "/Indicator-DrawdownDuration"
      },
      {
        "text": "GainLossRatio",
        "link": "/Indicator-GainLossRatio"
      },
      {
        "text": "InformationRatio",
        "link": "/Indicator-InformationRatio"
      },
      {
        "text": "KellyCriterion",
        "link": "/Indicator-KellyCriterion"
      },
      {
        "text": "MaxDrawdown",
        "link": "/Indicator-MaxDrawdown"
      },
      {
        "text": "OmegaRatio",
        "link": "/Indicator-OmegaRatio"
      },
      {
        "text": "PainIndex",
        "link": "/Indicator-PainIndex"
      },
      {
        "text": "ProfitFactor",
        "link": "/Indicator-ProfitFactor"
      },
      {
        "text": "RecoveryFactor",
        "link": "/Indicator-RecoveryFactor"
      },
      {
        "text": "SharpeRatio",
        "link": "/Indicator-SharpeRatio"
      },
      {
        "text": "SortinoRatio",
        "link": "/Indicator-SortinoRatio"
      },
      {
        "text": "TreynorRatio",
        "link": "/Indicator-TreynorRatio"
      },
      {
        "text": "ValueAtRisk",
        "link": "/Indicator-ValueAtRisk"
      }
    ]
  },
  {
    "text": "Microstructure",
    "collapsed": true,
    "items": [
      {
        "text": "CumulativeVolumeDelta",
        "link": "/Indicator-CumulativeVolumeDelta"
      },
      {
        "text": "DepthSlope",
        "link": "/Indicator-DepthSlope"
      },
      {
        "text": "EffectiveSpread",
        "link": "/Indicator-EffectiveSpread"
      },
      {
        "text": "Footprint",
        "link": "/Indicator-Footprint"
      },
      {
        "text": "KylesLambda",
        "link": "/Indicator-KylesLambda"
      },
      {
        "text": "Microprice",
        "link": "/Indicator-Microprice"
      },
      {
        "text": "OrderBookImbalanceFull",
        "link": "/Indicator-OrderBookImbalanceFull"
      },
      {
        "text": "OrderBookImbalanceTop1",
        "link": "/Indicator-OrderBookImbalanceTop1"
      },
      {
        "text": "OrderBookImbalanceTopN",
        "link": "/Indicator-OrderBookImbalanceTopN"
      },
      {
        "text": "QuotedSpread",
        "link": "/Indicator-QuotedSpread"
      },
      {
        "text": "RealizedSpread",
        "link": "/Indicator-RealizedSpread"
      },
      {
        "text": "SignedVolume",
        "link": "/Indicator-SignedVolume"
      },
      {
        "text": "TradeImbalance",
        "link": "/Indicator-TradeImbalance"
      }
    ]
  },
  {
    "text": "Derivatives",
    "collapsed": true,
    "items": [
      {
        "text": "CalendarSpread",
        "link": "/Indicator-CalendarSpread"
      },
      {
        "text": "FundingBasis",
        "link": "/Indicator-FundingBasis"
      },
      {
        "text": "FundingRate",
        "link": "/Indicator-FundingRate"
      },
      {
        "text": "FundingRateMean",
        "link": "/Indicator-FundingRateMean"
      },
      {
        "text": "FundingRateZScore",
        "link": "/Indicator-FundingRateZScore"
      },
      {
        "text": "LiquidationFeatures",
        "link": "/Indicator-LiquidationFeatures"
      },
      {
        "text": "LongShortRatio",
        "link": "/Indicator-LongShortRatio"
      },
      {
        "text": "OIPriceDivergence",
        "link": "/Indicator-OIPriceDivergence"
      },
      {
        "text": "OIWeighted",
        "link": "/Indicator-OIWeighted"
      },
      {
        "text": "OpenInterestDelta",
        "link": "/Indicator-OpenInterestDelta"
      },
      {
        "text": "TakerBuySellRatio",
        "link": "/Indicator-TakerBuySellRatio"
      },
      {
        "text": "TermStructureBasis",
        "link": "/Indicator-TermStructureBasis"
      }
    ]
  },
  {
    "text": "Alt-Chart Bars",
    "collapsed": true,
    "items": [
      {
        "text": "KagiBars",
        "link": "/Indicator-KagiBars"
      },
      {
        "text": "PointAndFigureBars",
        "link": "/Indicator-PointAndFigureBars"
      },
      {
        "text": "RenkoBars",
        "link": "/Indicator-RenkoBars"
      }
    ]
  }
]
