// AUTO-GENERATED by scripts/migrate-wiki.mjs from the wiki _Sidebar.md.
// Do not hand-edit — re-run `npm run migrate` instead.
export const sidebar = [
  {
    "text": "Getting started",
    "collapsed": false,
    "items": [
      {
        "text": "Quickstart: Rust",
        "link": "/Quickstart-Rust"
      },
      {
        "text": "Quickstart: Python",
        "link": "/Quickstart-Python"
      },
      {
        "text": "Quickstart: Node",
        "link": "/Quickstart-Node"
      },
      {
        "text": "Quickstart: WASM",
        "link": "/Quickstart-WASM"
      }
    ]
  },
  {
    "text": "Reference",
    "collapsed": false,
    "items": [
      {
        "text": "Indicators overview",
        "link": "/Indicators-Overview"
      },
      {
        "text": "Warmup periods",
        "link": "/Warmup-Periods"
      },
      {
        "text": "Streaming vs batch",
        "link": "/Streaming-vs-Batch"
      },
      {
        "text": "Indicator chaining",
        "link": "/Indicator-Chaining"
      },
      {
        "text": "Data layer",
        "link": "/Data-Layer"
      }
    ]
  },
  {
    "text": "Guides",
    "collapsed": false,
    "items": [
      {
        "text": "Cookbook",
        "link": "/Cookbook"
      },
      {
        "text": "TA-Lib migration",
        "link": "/TA-Lib-Migration"
      },
      {
        "text": "FAQ",
        "link": "/FAQ"
      }
    ]
  },
  {
    "text": "Moving Averages",
    "collapsed": true,
    "items": [
      {
        "text": "AdaptiveLaguerreFilter",
        "link": "/Indicators/Indicator-AdaptiveLaguerreFilter"
      },
      {
        "text": "Alligator",
        "link": "/Indicators/Indicator-Alligator"
      },
      {
        "text": "Alma",
        "link": "/Indicators/Indicator-Alma"
      },
      {
        "text": "Dema",
        "link": "/Indicators/Indicator-Dema"
      },
      {
        "text": "Ehma",
        "link": "/Indicators/Indicator-Ehma"
      },
      {
        "text": "Ema",
        "link": "/Indicators/Indicator-Ema"
      },
      {
        "text": "Evwma",
        "link": "/Indicators/Indicator-Evwma"
      },
      {
        "text": "Frama",
        "link": "/Indicators/Indicator-Frama"
      },
      {
        "text": "GeneralizedDema",
        "link": "/Indicators/Indicator-GeneralizedDema"
      },
      {
        "text": "GeometricMa",
        "link": "/Indicators/Indicator-GeometricMa"
      },
      {
        "text": "Hma",
        "link": "/Indicators/Indicator-Hma"
      },
      {
        "text": "HoltWinters",
        "link": "/Indicators/Indicator-HoltWinters"
      },
      {
        "text": "Jma",
        "link": "/Indicators/Indicator-Jma"
      },
      {
        "text": "Kama",
        "link": "/Indicators/Indicator-Kama"
      },
      {
        "text": "McGinleyDynamic",
        "link": "/Indicators/Indicator-McGinleyDynamic"
      },
      {
        "text": "MedianMa",
        "link": "/Indicators/Indicator-MedianMa"
      },
      {
        "text": "SineWeightedMa",
        "link": "/Indicators/Indicator-SineWeightedMa"
      },
      {
        "text": "Sma",
        "link": "/Indicators/Indicator-Sma"
      },
      {
        "text": "Smma",
        "link": "/Indicators/Indicator-Smma"
      },
      {
        "text": "T3",
        "link": "/Indicators/Indicator-T3"
      },
      {
        "text": "Tema",
        "link": "/Indicators/Indicator-Tema"
      },
      {
        "text": "Trima",
        "link": "/Indicators/Indicator-Trima"
      },
      {
        "text": "Vidya",
        "link": "/Indicators/Indicator-Vidya"
      },
      {
        "text": "Vwma",
        "link": "/Indicators/Indicator-Vwma"
      },
      {
        "text": "Wma",
        "link": "/Indicators/Indicator-Wma"
      },
      {
        "text": "Zlema",
        "link": "/Indicators/Indicator-Zlema"
      }
    ]
  },
  {
    "text": "Momentum Oscillators",
    "collapsed": true,
    "items": [
      {
        "text": "AnchoredRsi",
        "link": "/Indicators/Indicator-AnchoredRsi"
      },
      {
        "text": "AwesomeOscillator",
        "link": "/Indicators/Indicator-AwesomeOscillator"
      },
      {
        "text": "Cci",
        "link": "/Indicators/Indicator-Cci"
      },
      {
        "text": "Cmo",
        "link": "/Indicators/Indicator-Cmo"
      },
      {
        "text": "ConnorsRsi",
        "link": "/Indicators/Indicator-ConnorsRsi"
      },
      {
        "text": "DerivativeOscillator",
        "link": "/Indicators/Indicator-DerivativeOscillator"
      },
      {
        "text": "DisparityIndex",
        "link": "/Indicators/Indicator-DisparityIndex"
      },
      {
        "text": "DynamicMomentumIndex",
        "link": "/Indicators/Indicator-DynamicMomentumIndex"
      },
      {
        "text": "ElderRay",
        "link": "/Indicators/Indicator-ElderRay"
      },
      {
        "text": "FisherRsi",
        "link": "/Indicators/Indicator-FisherRsi"
      },
      {
        "text": "Inertia",
        "link": "/Indicators/Indicator-Inertia"
      },
      {
        "text": "IntradayMomentumIndex",
        "link": "/Indicators/Indicator-IntradayMomentumIndex"
      },
      {
        "text": "Kst",
        "link": "/Indicators/Indicator-Kst"
      },
      {
        "text": "LaguerreRsi",
        "link": "/Indicators/Indicator-LaguerreRsi"
      },
      {
        "text": "Mfi",
        "link": "/Indicators/Indicator-Mfi"
      },
      {
        "text": "Mom",
        "link": "/Indicators/Indicator-Mom"
      },
      {
        "text": "Pgo",
        "link": "/Indicators/Indicator-Pgo"
      },
      {
        "text": "Pmo",
        "link": "/Indicators/Indicator-Pmo"
      },
      {
        "text": "Qqe",
        "link": "/Indicators/Indicator-Qqe"
      },
      {
        "text": "Rmi",
        "link": "/Indicators/Indicator-Rmi"
      },
      {
        "text": "Roc",
        "link": "/Indicators/Indicator-Roc"
      },
      {
        "text": "Rocp",
        "link": "/Indicators/Indicator-Rocp"
      },
      {
        "text": "Rocr",
        "link": "/Indicators/Indicator-Rocr"
      },
      {
        "text": "Rocr100",
        "link": "/Indicators/Indicator-Rocr100"
      },
      {
        "text": "Rsi",
        "link": "/Indicators/Indicator-Rsi"
      },
      {
        "text": "Rsx",
        "link": "/Indicators/Indicator-Rsx"
      },
      {
        "text": "Rvi",
        "link": "/Indicators/Indicator-Rvi"
      },
      {
        "text": "Smi",
        "link": "/Indicators/Indicator-Smi"
      },
      {
        "text": "Stochastic",
        "link": "/Indicators/Indicator-Stochastic"
      },
      {
        "text": "StochasticCci",
        "link": "/Indicators/Indicator-StochasticCci"
      },
      {
        "text": "StochRsi",
        "link": "/Indicators/Indicator-StochRsi"
      },
      {
        "text": "Tsi",
        "link": "/Indicators/Indicator-Tsi"
      },
      {
        "text": "UltimateOscillator",
        "link": "/Indicators/Indicator-UltimateOscillator"
      },
      {
        "text": "WilliamsR",
        "link": "/Indicators/Indicator-WilliamsR"
      }
    ]
  },
  {
    "text": "Trend & Directional",
    "collapsed": true,
    "items": [
      {
        "text": "Adx",
        "link": "/Indicators/Indicator-Adx"
      },
      {
        "text": "Adxr",
        "link": "/Indicators/Indicator-Adxr"
      },
      {
        "text": "Aroon",
        "link": "/Indicators/Indicator-Aroon"
      },
      {
        "text": "AroonOscillator",
        "link": "/Indicators/Indicator-AroonOscillator"
      },
      {
        "text": "ChoppinessIndex",
        "link": "/Indicators/Indicator-ChoppinessIndex"
      },
      {
        "text": "Dx",
        "link": "/Indicators/Indicator-Dx"
      },
      {
        "text": "GatorOscillator",
        "link": "/Indicators/Indicator-GatorOscillator"
      },
      {
        "text": "KasePermissionStochastic",
        "link": "/Indicators/Indicator-KasePermissionStochastic"
      },
      {
        "text": "MacdExt",
        "link": "/Indicators/Indicator-MacdExt"
      },
      {
        "text": "MacdFix",
        "link": "/Indicators/Indicator-MacdFix"
      },
      {
        "text": "MacdIndicator",
        "link": "/Indicators/Indicator-MacdIndicator"
      },
      {
        "text": "MassIndex",
        "link": "/Indicators/Indicator-MassIndex"
      },
      {
        "text": "MinusDi",
        "link": "/Indicators/Indicator-MinusDi"
      },
      {
        "text": "MinusDm",
        "link": "/Indicators/Indicator-MinusDm"
      },
      {
        "text": "PlusDi",
        "link": "/Indicators/Indicator-PlusDi"
      },
      {
        "text": "PlusDm",
        "link": "/Indicators/Indicator-PlusDm"
      },
      {
        "text": "PolarizedFractalEfficiency",
        "link": "/Indicators/Indicator-PolarizedFractalEfficiency"
      },
      {
        "text": "Qstick",
        "link": "/Indicators/Indicator-Qstick"
      },
      {
        "text": "Rwi",
        "link": "/Indicators/Indicator-Rwi"
      },
      {
        "text": "Tii",
        "link": "/Indicators/Indicator-Tii"
      },
      {
        "text": "TrendStrengthIndex",
        "link": "/Indicators/Indicator-TrendStrengthIndex"
      },
      {
        "text": "Trix",
        "link": "/Indicators/Indicator-Trix"
      },
      {
        "text": "TtmTrend",
        "link": "/Indicators/Indicator-TtmTrend"
      },
      {
        "text": "VerticalHorizontalFilter",
        "link": "/Indicators/Indicator-VerticalHorizontalFilter"
      },
      {
        "text": "Vortex",
        "link": "/Indicators/Indicator-Vortex"
      },
      {
        "text": "WavePm",
        "link": "/Indicators/Indicator-WavePm"
      },
      {
        "text": "WaveTrend",
        "link": "/Indicators/Indicator-WaveTrend"
      },
      {
        "text": "TrendLabel",
        "link": "/Indicators/Indicator-TrendLabel"
      }
    ]
  },
  {
    "text": "Price Oscillators",
    "collapsed": true,
    "items": [
      {
        "text": "AcceleratorOscillator",
        "link": "/Indicators/Indicator-AcceleratorOscillator"
      },
      {
        "text": "Apo",
        "link": "/Indicators/Indicator-Apo"
      },
      {
        "text": "AwesomeOscillatorHistogram",
        "link": "/Indicators/Indicator-AwesomeOscillatorHistogram"
      },
      {
        "text": "BalanceOfPower",
        "link": "/Indicators/Indicator-BalanceOfPower"
      },
      {
        "text": "Cfo",
        "link": "/Indicators/Indicator-Cfo"
      },
      {
        "text": "Coppock",
        "link": "/Indicators/Indicator-Coppock"
      },
      {
        "text": "Dpo",
        "link": "/Indicators/Indicator-Dpo"
      },
      {
        "text": "ElderImpulse",
        "link": "/Indicators/Indicator-ElderImpulse"
      },
      {
        "text": "MacdHistogram",
        "link": "/Indicators/Indicator-MacdHistogram"
      },
      {
        "text": "Ppo",
        "link": "/Indicators/Indicator-Ppo"
      },
      {
        "text": "PpoHistogram",
        "link": "/Indicators/Indicator-PpoHistogram"
      },
      {
        "text": "Stc",
        "link": "/Indicators/Indicator-Stc"
      },
      {
        "text": "TsfOscillator",
        "link": "/Indicators/Indicator-TsfOscillator"
      },
      {
        "text": "ZeroLagMacd",
        "link": "/Indicators/Indicator-ZeroLagMacd"
      }
    ]
  },
  {
    "text": "Volatility & Bands",
    "collapsed": true,
    "items": [
      {
        "text": "Atr",
        "link": "/Indicators/Indicator-Atr"
      },
      {
        "text": "BollingerBands",
        "link": "/Indicators/Indicator-BollingerBands"
      },
      {
        "text": "BollingerBandwidth",
        "link": "/Indicators/Indicator-BollingerBandwidth"
      },
      {
        "text": "ChaikinVolatility",
        "link": "/Indicators/Indicator-ChaikinVolatility"
      },
      {
        "text": "DetrendedStdDev",
        "link": "/Indicators/Indicator-DetrendedStdDev"
      },
      {
        "text": "Donchian",
        "link": "/Indicators/Indicator-Donchian"
      },
      {
        "text": "GarmanKlassVolatility",
        "link": "/Indicators/Indicator-GarmanKlassVolatility"
      },
      {
        "text": "HistoricalVolatility",
        "link": "/Indicators/Indicator-HistoricalVolatility"
      },
      {
        "text": "Keltner",
        "link": "/Indicators/Indicator-Keltner"
      },
      {
        "text": "Natr",
        "link": "/Indicators/Indicator-Natr"
      },
      {
        "text": "ParkinsonVolatility",
        "link": "/Indicators/Indicator-ParkinsonVolatility"
      },
      {
        "text": "PercentB",
        "link": "/Indicators/Indicator-PercentB"
      },
      {
        "text": "RogersSatchellVolatility",
        "link": "/Indicators/Indicator-RogersSatchellVolatility"
      },
      {
        "text": "RviVolatility",
        "link": "/Indicators/Indicator-RviVolatility"
      },
      {
        "text": "StdDev",
        "link": "/Indicators/Indicator-StdDev"
      },
      {
        "text": "TrueRange",
        "link": "/Indicators/Indicator-TrueRange"
      },
      {
        "text": "UlcerIndex",
        "link": "/Indicators/Indicator-UlcerIndex"
      },
      {
        "text": "YangZhangVolatility",
        "link": "/Indicators/Indicator-YangZhangVolatility"
      },
      {
        "text": "JumpIndicator",
        "link": "/Indicators/Indicator-JumpIndicator"
      },
      {
        "text": "RegimeLabel",
        "link": "/Indicators/Indicator-RegimeLabel"
      }
    ]
  },
  {
    "text": "Bands & Channels",
    "collapsed": true,
    "items": [
      {
        "text": "AccelerationBands",
        "link": "/Indicators/Indicator-AccelerationBands"
      },
      {
        "text": "AtrBands",
        "link": "/Indicators/Indicator-AtrBands"
      },
      {
        "text": "DoubleBollinger",
        "link": "/Indicators/Indicator-DoubleBollinger"
      },
      {
        "text": "FractalChaosBands",
        "link": "/Indicators/Indicator-FractalChaosBands"
      },
      {
        "text": "HurstChannel",
        "link": "/Indicators/Indicator-HurstChannel"
      },
      {
        "text": "LinRegChannel",
        "link": "/Indicators/Indicator-LinRegChannel"
      },
      {
        "text": "MaEnvelope",
        "link": "/Indicators/Indicator-MaEnvelope"
      },
      {
        "text": "StandardErrorBands",
        "link": "/Indicators/Indicator-StandardErrorBands"
      },
      {
        "text": "StarcBands",
        "link": "/Indicators/Indicator-StarcBands"
      },
      {
        "text": "TtmSqueeze",
        "link": "/Indicators/Indicator-TtmSqueeze"
      },
      {
        "text": "VwapStdDevBands",
        "link": "/Indicators/Indicator-VwapStdDevBands"
      }
    ]
  },
  {
    "text": "Trailing Stops",
    "collapsed": true,
    "items": [
      {
        "text": "AtrTrailingStop",
        "link": "/Indicators/Indicator-AtrTrailingStop"
      },
      {
        "text": "ChandeKrollStop",
        "link": "/Indicators/Indicator-ChandeKrollStop"
      },
      {
        "text": "ChandelierExit",
        "link": "/Indicators/Indicator-ChandelierExit"
      },
      {
        "text": "DonchianStop",
        "link": "/Indicators/Indicator-DonchianStop"
      },
      {
        "text": "HiLoActivator",
        "link": "/Indicators/Indicator-HiLoActivator"
      },
      {
        "text": "PercentageTrailingStop",
        "link": "/Indicators/Indicator-PercentageTrailingStop"
      },
      {
        "text": "Psar",
        "link": "/Indicators/Indicator-Psar"
      },
      {
        "text": "RenkoTrailingStop",
        "link": "/Indicators/Indicator-RenkoTrailingStop"
      },
      {
        "text": "SarExt",
        "link": "/Indicators/Indicator-SarExt"
      },
      {
        "text": "StepTrailingStop",
        "link": "/Indicators/Indicator-StepTrailingStop"
      },
      {
        "text": "SuperTrend",
        "link": "/Indicators/Indicator-SuperTrend"
      },
      {
        "text": "VoltyStop",
        "link": "/Indicators/Indicator-VoltyStop"
      },
      {
        "text": "YoyoExit",
        "link": "/Indicators/Indicator-YoyoExit"
      }
    ]
  },
  {
    "text": "Volume",
    "collapsed": true,
    "items": [
      {
        "text": "AdOscillator",
        "link": "/Indicators/Indicator-AdOscillator"
      },
      {
        "text": "Adl",
        "link": "/Indicators/Indicator-Adl"
      },
      {
        "text": "AnchoredVwap",
        "link": "/Indicators/Indicator-AnchoredVwap"
      },
      {
        "text": "ChaikinMoneyFlow",
        "link": "/Indicators/Indicator-ChaikinMoneyFlow"
      },
      {
        "text": "ChaikinOscillator",
        "link": "/Indicators/Indicator-ChaikinOscillator"
      },
      {
        "text": "DemandIndex",
        "link": "/Indicators/Indicator-DemandIndex"
      },
      {
        "text": "EaseOfMovement",
        "link": "/Indicators/Indicator-EaseOfMovement"
      },
      {
        "text": "ForceIndex",
        "link": "/Indicators/Indicator-ForceIndex"
      },
      {
        "text": "Kvo",
        "link": "/Indicators/Indicator-Kvo"
      },
      {
        "text": "MarketFacilitationIndex",
        "link": "/Indicators/Indicator-MarketFacilitationIndex"
      },
      {
        "text": "Nvi",
        "link": "/Indicators/Indicator-Nvi"
      },
      {
        "text": "Obv",
        "link": "/Indicators/Indicator-Obv"
      },
      {
        "text": "Pvi",
        "link": "/Indicators/Indicator-Pvi"
      },
      {
        "text": "RollingVwap",
        "link": "/Indicators/Indicator-RollingVwap"
      },
      {
        "text": "Tsv",
        "link": "/Indicators/Indicator-Tsv"
      },
      {
        "text": "VolumeOscillator",
        "link": "/Indicators/Indicator-VolumeOscillator"
      },
      {
        "text": "VolumePriceTrend",
        "link": "/Indicators/Indicator-VolumePriceTrend"
      },
      {
        "text": "Vwap",
        "link": "/Indicators/Indicator-Vwap"
      },
      {
        "text": "Vzo",
        "link": "/Indicators/Indicator-Vzo"
      }
    ]
  },
  {
    "text": "Price Statistics",
    "collapsed": true,
    "items": [
      {
        "text": "Autocorrelation",
        "link": "/Indicators/Indicator-Autocorrelation"
      },
      {
        "text": "AvgPrice",
        "link": "/Indicators/Indicator-AvgPrice"
      },
      {
        "text": "Beta",
        "link": "/Indicators/Indicator-Beta"
      },
      {
        "text": "CoefficientOfVariation",
        "link": "/Indicators/Indicator-CoefficientOfVariation"
      },
      {
        "text": "Cointegration",
        "link": "/Indicators/Indicator-Cointegration"
      },
      {
        "text": "HurstExponent",
        "link": "/Indicators/Indicator-HurstExponent"
      },
      {
        "text": "Kurtosis",
        "link": "/Indicators/Indicator-Kurtosis"
      },
      {
        "text": "LeadLagCrossCorrelation",
        "link": "/Indicators/Indicator-LeadLagCrossCorrelation"
      },
      {
        "text": "LinearRegression",
        "link": "/Indicators/Indicator-LinearRegression"
      },
      {
        "text": "LinRegAngle",
        "link": "/Indicators/Indicator-LinRegAngle"
      },
      {
        "text": "LinRegIntercept",
        "link": "/Indicators/Indicator-LinRegIntercept"
      },
      {
        "text": "LinRegSlope",
        "link": "/Indicators/Indicator-LinRegSlope"
      },
      {
        "text": "MedianAbsoluteDeviation",
        "link": "/Indicators/Indicator-MedianAbsoluteDeviation"
      },
      {
        "text": "MedianPrice",
        "link": "/Indicators/Indicator-MedianPrice"
      },
      {
        "text": "MidPoint",
        "link": "/Indicators/Indicator-MidPoint"
      },
      {
        "text": "MidPrice",
        "link": "/Indicators/Indicator-MidPrice"
      },
      {
        "text": "PairSpreadZScore",
        "link": "/Indicators/Indicator-PairSpreadZScore"
      },
      {
        "text": "PairwiseBeta",
        "link": "/Indicators/Indicator-PairwiseBeta"
      },
      {
        "text": "PearsonCorrelation",
        "link": "/Indicators/Indicator-PearsonCorrelation"
      },
      {
        "text": "RelativeStrengthAB",
        "link": "/Indicators/Indicator-RelativeStrengthAB"
      },
      {
        "text": "RSquared",
        "link": "/Indicators/Indicator-RSquared"
      },
      {
        "text": "Skewness",
        "link": "/Indicators/Indicator-Skewness"
      },
      {
        "text": "SpearmanCorrelation",
        "link": "/Indicators/Indicator-SpearmanCorrelation"
      },
      {
        "text": "StandardError",
        "link": "/Indicators/Indicator-StandardError"
      },
      {
        "text": "Tsf",
        "link": "/Indicators/Indicator-Tsf"
      },
      {
        "text": "TypicalPrice",
        "link": "/Indicators/Indicator-TypicalPrice"
      },
      {
        "text": "Variance",
        "link": "/Indicators/Indicator-Variance"
      },
      {
        "text": "WeightedClose",
        "link": "/Indicators/Indicator-WeightedClose"
      },
      {
        "text": "ZScore",
        "link": "/Indicators/Indicator-ZScore"
      },
      {
        "text": "BodySizePct",
        "link": "/Indicators/Indicator-BodySizePct"
      },
      {
        "text": "CloseVsOpen",
        "link": "/Indicators/Indicator-CloseVsOpen"
      },
      {
        "text": "HighLowRange",
        "link": "/Indicators/Indicator-HighLowRange"
      },
      {
        "text": "LogReturn",
        "link": "/Indicators/Indicator-LogReturn"
      },
      {
        "text": "RealizedVolatility",
        "link": "/Indicators/Indicator-RealizedVolatility"
      },
      {
        "text": "RollingIqr",
        "link": "/Indicators/Indicator-RollingIqr"
      },
      {
        "text": "RollingPercentileRank",
        "link": "/Indicators/Indicator-RollingPercentileRank"
      },
      {
        "text": "RollingQuantile",
        "link": "/Indicators/Indicator-RollingQuantile"
      },
      {
        "text": "SpreadAr1Coefficient",
        "link": "/Indicators/Indicator-SpreadAr1Coefficient"
      },
      {
        "text": "WickRatio",
        "link": "/Indicators/Indicator-WickRatio"
      },
      {
        "text": "BetaNeutralSpread",
        "link": "/Indicators/Indicator-BetaNeutralSpread"
      },
      {
        "text": "DistanceSsd",
        "link": "/Indicators/Indicator-DistanceSsd"
      },
      {
        "text": "GrangerCausality",
        "link": "/Indicators/Indicator-GrangerCausality"
      },
      {
        "text": "KalmanHedgeRatio",
        "link": "/Indicators/Indicator-KalmanHedgeRatio"
      },
      {
        "text": "OuHalfLife",
        "link": "/Indicators/Indicator-OuHalfLife"
      },
      {
        "text": "RollingCorrelation",
        "link": "/Indicators/Indicator-RollingCorrelation"
      },
      {
        "text": "RollingCovariance",
        "link": "/Indicators/Indicator-RollingCovariance"
      },
      {
        "text": "SpreadBollingerBands",
        "link": "/Indicators/Indicator-SpreadBollingerBands"
      },
      {
        "text": "SpreadHurst",
        "link": "/Indicators/Indicator-SpreadHurst"
      },
      {
        "text": "VarianceRatio",
        "link": "/Indicators/Indicator-VarianceRatio"
      }
    ]
  },
  {
    "text": "Market Profile",
    "collapsed": true,
    "items": [
      {
        "text": "InitialBalance",
        "link": "/Indicators/Indicator-InitialBalance"
      },
      {
        "text": "OpeningRange",
        "link": "/Indicators/Indicator-OpeningRange"
      },
      {
        "text": "TpoProfile",
        "link": "/Indicators/Indicator-TpoProfile"
      },
      {
        "text": "ValueArea",
        "link": "/Indicators/Indicator-ValueArea"
      },
      {
        "text": "VolumeProfile",
        "link": "/Indicators/Indicator-VolumeProfile"
      }
    ]
  },
  {
    "text": "Ichimoku & Charts",
    "collapsed": true,
    "items": [
      {
        "text": "HeikinAshi",
        "link": "/Indicators/Indicator-HeikinAshi"
      },
      {
        "text": "Ichimoku",
        "link": "/Indicators/Indicator-Ichimoku"
      }
    ]
  },
  {
    "text": "Pivots & S/R",
    "collapsed": true,
    "items": [
      {
        "text": "Camarilla",
        "link": "/Indicators/Indicator-Camarilla"
      },
      {
        "text": "ClassicPivots",
        "link": "/Indicators/Indicator-ClassicPivots"
      },
      {
        "text": "DemarkPivots",
        "link": "/Indicators/Indicator-DemarkPivots"
      },
      {
        "text": "FibonacciPivots",
        "link": "/Indicators/Indicator-FibonacciPivots"
      },
      {
        "text": "WilliamsFractals",
        "link": "/Indicators/Indicator-WilliamsFractals"
      },
      {
        "text": "WoodiePivots",
        "link": "/Indicators/Indicator-WoodiePivots"
      },
      {
        "text": "ZigZag",
        "link": "/Indicators/Indicator-ZigZag"
      }
    ]
  },
  {
    "text": "DeMark",
    "collapsed": true,
    "items": [
      {
        "text": "TdCombo",
        "link": "/Indicators/Indicator-TdCombo"
      },
      {
        "text": "TdCountdown",
        "link": "/Indicators/Indicator-TdCountdown"
      },
      {
        "text": "TdDeMarker",
        "link": "/Indicators/Indicator-TdDeMarker"
      },
      {
        "text": "TdDifferential",
        "link": "/Indicators/Indicator-TdDifferential"
      },
      {
        "text": "TdLines",
        "link": "/Indicators/Indicator-TdLines"
      },
      {
        "text": "TdOpen",
        "link": "/Indicators/Indicator-TdOpen"
      },
      {
        "text": "TdPressure",
        "link": "/Indicators/Indicator-TdPressure"
      },
      {
        "text": "TdRangeProjection",
        "link": "/Indicators/Indicator-TdRangeProjection"
      },
      {
        "text": "TdRei",
        "link": "/Indicators/Indicator-TdRei"
      },
      {
        "text": "TdRiskLevel",
        "link": "/Indicators/Indicator-TdRiskLevel"
      },
      {
        "text": "TdSequential",
        "link": "/Indicators/Indicator-TdSequential"
      },
      {
        "text": "TdSetup",
        "link": "/Indicators/Indicator-TdSetup"
      }
    ]
  },
  {
    "text": "Candlestick Patterns",
    "collapsed": true,
    "items": [
      {
        "text": "AbandonedBaby",
        "link": "/Indicators/Indicator-AbandonedBaby"
      },
      {
        "text": "AdvanceBlock",
        "link": "/Indicators/Indicator-AdvanceBlock"
      },
      {
        "text": "BeltHold",
        "link": "/Indicators/Indicator-BeltHold"
      },
      {
        "text": "Breakaway",
        "link": "/Indicators/Indicator-Breakaway"
      },
      {
        "text": "ClosingMarubozu",
        "link": "/Indicators/Indicator-ClosingMarubozu"
      },
      {
        "text": "ConcealingBabySwallow",
        "link": "/Indicators/Indicator-ConcealingBabySwallow"
      },
      {
        "text": "Counterattack",
        "link": "/Indicators/Indicator-Counterattack"
      },
      {
        "text": "Doji",
        "link": "/Indicators/Indicator-Doji"
      },
      {
        "text": "DojiStar",
        "link": "/Indicators/Indicator-DojiStar"
      },
      {
        "text": "DownsideGapThreeMethods",
        "link": "/Indicators/Indicator-DownsideGapThreeMethods"
      },
      {
        "text": "DragonflyDoji",
        "link": "/Indicators/Indicator-DragonflyDoji"
      },
      {
        "text": "Engulfing",
        "link": "/Indicators/Indicator-Engulfing"
      },
      {
        "text": "EveningDojiStar",
        "link": "/Indicators/Indicator-EveningDojiStar"
      },
      {
        "text": "FallingThreeMethods",
        "link": "/Indicators/Indicator-FallingThreeMethods"
      },
      {
        "text": "GapSideBySideWhite",
        "link": "/Indicators/Indicator-GapSideBySideWhite"
      },
      {
        "text": "GravestoneDoji",
        "link": "/Indicators/Indicator-GravestoneDoji"
      },
      {
        "text": "Hammer",
        "link": "/Indicators/Indicator-Hammer"
      },
      {
        "text": "HangingMan",
        "link": "/Indicators/Indicator-HangingMan"
      },
      {
        "text": "Harami",
        "link": "/Indicators/Indicator-Harami"
      },
      {
        "text": "HighWave",
        "link": "/Indicators/Indicator-HighWave"
      },
      {
        "text": "Hikkake",
        "link": "/Indicators/Indicator-Hikkake"
      },
      {
        "text": "HikkakeModified",
        "link": "/Indicators/Indicator-HikkakeModified"
      },
      {
        "text": "HomingPigeon",
        "link": "/Indicators/Indicator-HomingPigeon"
      },
      {
        "text": "IdenticalThreeCrows",
        "link": "/Indicators/Indicator-IdenticalThreeCrows"
      },
      {
        "text": "InNeck",
        "link": "/Indicators/Indicator-InNeck"
      },
      {
        "text": "InvertedHammer",
        "link": "/Indicators/Indicator-InvertedHammer"
      },
      {
        "text": "Kicking",
        "link": "/Indicators/Indicator-Kicking"
      },
      {
        "text": "KickingByLength",
        "link": "/Indicators/Indicator-KickingByLength"
      },
      {
        "text": "LadderBottom",
        "link": "/Indicators/Indicator-LadderBottom"
      },
      {
        "text": "LongLeggedDoji",
        "link": "/Indicators/Indicator-LongLeggedDoji"
      },
      {
        "text": "LongLine",
        "link": "/Indicators/Indicator-LongLine"
      },
      {
        "text": "Marubozu",
        "link": "/Indicators/Indicator-Marubozu"
      },
      {
        "text": "MatchingLow",
        "link": "/Indicators/Indicator-MatchingLow"
      },
      {
        "text": "MatHold",
        "link": "/Indicators/Indicator-MatHold"
      },
      {
        "text": "MorningDojiStar",
        "link": "/Indicators/Indicator-MorningDojiStar"
      },
      {
        "text": "MorningEveningStar",
        "link": "/Indicators/Indicator-MorningEveningStar"
      },
      {
        "text": "OnNeck",
        "link": "/Indicators/Indicator-OnNeck"
      },
      {
        "text": "OpeningMarubozu",
        "link": "/Indicators/Indicator-OpeningMarubozu"
      },
      {
        "text": "PiercingDarkCloud",
        "link": "/Indicators/Indicator-PiercingDarkCloud"
      },
      {
        "text": "RickshawMan",
        "link": "/Indicators/Indicator-RickshawMan"
      },
      {
        "text": "RisingThreeMethods",
        "link": "/Indicators/Indicator-RisingThreeMethods"
      },
      {
        "text": "SeparatingLines",
        "link": "/Indicators/Indicator-SeparatingLines"
      },
      {
        "text": "ShootingStar",
        "link": "/Indicators/Indicator-ShootingStar"
      },
      {
        "text": "ShortLine",
        "link": "/Indicators/Indicator-ShortLine"
      },
      {
        "text": "SpinningTop",
        "link": "/Indicators/Indicator-SpinningTop"
      },
      {
        "text": "StalledPattern",
        "link": "/Indicators/Indicator-StalledPattern"
      },
      {
        "text": "StickSandwich",
        "link": "/Indicators/Indicator-StickSandwich"
      },
      {
        "text": "Takuri",
        "link": "/Indicators/Indicator-Takuri"
      },
      {
        "text": "TasukiGap",
        "link": "/Indicators/Indicator-TasukiGap"
      },
      {
        "text": "ThreeInside",
        "link": "/Indicators/Indicator-ThreeInside"
      },
      {
        "text": "ThreeLineStrike",
        "link": "/Indicators/Indicator-ThreeLineStrike"
      },
      {
        "text": "ThreeOutside",
        "link": "/Indicators/Indicator-ThreeOutside"
      },
      {
        "text": "ThreeSoldiersOrCrows",
        "link": "/Indicators/Indicator-ThreeSoldiersOrCrows"
      },
      {
        "text": "ThreeStarsInSouth",
        "link": "/Indicators/Indicator-ThreeStarsInSouth"
      },
      {
        "text": "Thrusting",
        "link": "/Indicators/Indicator-Thrusting"
      },
      {
        "text": "Tweezer",
        "link": "/Indicators/Indicator-Tweezer"
      },
      {
        "text": "TwoCrows",
        "link": "/Indicators/Indicator-TwoCrows"
      },
      {
        "text": "UniqueThreeRiver",
        "link": "/Indicators/Indicator-UniqueThreeRiver"
      },
      {
        "text": "UpsideGapThreeMethods",
        "link": "/Indicators/Indicator-UpsideGapThreeMethods"
      },
      {
        "text": "UpsideGapTwoCrows",
        "link": "/Indicators/Indicator-UpsideGapTwoCrows"
      }
    ]
  },
  {
    "text": "Chart Patterns",
    "collapsed": true,
    "items": [
      {
        "text": "CupAndHandle",
        "link": "/Indicators/Indicator-CupAndHandle"
      },
      {
        "text": "DoubleTopBottom",
        "link": "/Indicators/Indicator-DoubleTopBottom"
      },
      {
        "text": "FlagPennant",
        "link": "/Indicators/Indicator-FlagPennant"
      },
      {
        "text": "HeadAndShoulders",
        "link": "/Indicators/Indicator-HeadAndShoulders"
      },
      {
        "text": "RectangleRange",
        "link": "/Indicators/Indicator-RectangleRange"
      },
      {
        "text": "Triangle",
        "link": "/Indicators/Indicator-Triangle"
      },
      {
        "text": "TripleTopBottom",
        "link": "/Indicators/Indicator-TripleTopBottom"
      },
      {
        "text": "Wedge",
        "link": "/Indicators/Indicator-Wedge"
      }
    ]
  },
  {
    "text": "Harmonic Patterns",
    "collapsed": true,
    "items": [
      {
        "text": "Abcd",
        "link": "/Indicators/Indicator-Abcd"
      },
      {
        "text": "Bat",
        "link": "/Indicators/Indicator-Bat"
      },
      {
        "text": "Butterfly",
        "link": "/Indicators/Indicator-Butterfly"
      },
      {
        "text": "Crab",
        "link": "/Indicators/Indicator-Crab"
      },
      {
        "text": "Cypher",
        "link": "/Indicators/Indicator-Cypher"
      },
      {
        "text": "Gartley",
        "link": "/Indicators/Indicator-Gartley"
      },
      {
        "text": "Shark",
        "link": "/Indicators/Indicator-Shark"
      },
      {
        "text": "ThreeDrives",
        "link": "/Indicators/Indicator-ThreeDrives"
      }
    ]
  },
  {
    "text": "Fibonacci",
    "collapsed": true,
    "items": [
      {
        "text": "AutoFib",
        "link": "/Indicators/Indicator-AutoFib"
      },
      {
        "text": "FibArcs",
        "link": "/Indicators/Indicator-FibArcs"
      },
      {
        "text": "FibChannel",
        "link": "/Indicators/Indicator-FibChannel"
      },
      {
        "text": "FibConfluence",
        "link": "/Indicators/Indicator-FibConfluence"
      },
      {
        "text": "FibExtension",
        "link": "/Indicators/Indicator-FibExtension"
      },
      {
        "text": "FibFan",
        "link": "/Indicators/Indicator-FibFan"
      },
      {
        "text": "FibProjection",
        "link": "/Indicators/Indicator-FibProjection"
      },
      {
        "text": "FibRetracement",
        "link": "/Indicators/Indicator-FibRetracement"
      },
      {
        "text": "FibTimeZones",
        "link": "/Indicators/Indicator-FibTimeZones"
      },
      {
        "text": "GoldenPocket",
        "link": "/Indicators/Indicator-GoldenPocket"
      }
    ]
  },
  {
    "text": "Ehlers / Cycle (DSP)",
    "collapsed": true,
    "items": [
      {
        "text": "AdaptiveCycle",
        "link": "/Indicators/Indicator-AdaptiveCycle"
      },
      {
        "text": "CenterOfGravity",
        "link": "/Indicators/Indicator-CenterOfGravity"
      },
      {
        "text": "CyberneticCycle",
        "link": "/Indicators/Indicator-CyberneticCycle"
      },
      {
        "text": "Decycler",
        "link": "/Indicators/Indicator-Decycler"
      },
      {
        "text": "DecyclerOscillator",
        "link": "/Indicators/Indicator-DecyclerOscillator"
      },
      {
        "text": "EhlersStochastic",
        "link": "/Indicators/Indicator-EhlersStochastic"
      },
      {
        "text": "EmpiricalModeDecomposition",
        "link": "/Indicators/Indicator-EmpiricalModeDecomposition"
      },
      {
        "text": "Fama",
        "link": "/Indicators/Indicator-Fama"
      },
      {
        "text": "FisherTransform",
        "link": "/Indicators/Indicator-FisherTransform"
      },
      {
        "text": "HilbertDominantCycle",
        "link": "/Indicators/Indicator-HilbertDominantCycle"
      },
      {
        "text": "HtDcPhase",
        "link": "/Indicators/Indicator-HtDcPhase"
      },
      {
        "text": "HtPhasor",
        "link": "/Indicators/Indicator-HtPhasor"
      },
      {
        "text": "HtTrendMode",
        "link": "/Indicators/Indicator-HtTrendMode"
      },
      {
        "text": "InstantaneousTrendline",
        "link": "/Indicators/Indicator-InstantaneousTrendline"
      },
      {
        "text": "InverseFisherTransform",
        "link": "/Indicators/Indicator-InverseFisherTransform"
      },
      {
        "text": "Mama",
        "link": "/Indicators/Indicator-Mama"
      },
      {
        "text": "RoofingFilter",
        "link": "/Indicators/Indicator-RoofingFilter"
      },
      {
        "text": "SineWave",
        "link": "/Indicators/Indicator-SineWave"
      },
      {
        "text": "SuperSmoother",
        "link": "/Indicators/Indicator-SuperSmoother"
      }
    ]
  },
  {
    "text": "Risk / Performance",
    "collapsed": true,
    "items": [
      {
        "text": "Alpha",
        "link": "/Indicators/Indicator-Alpha"
      },
      {
        "text": "AverageDrawdown",
        "link": "/Indicators/Indicator-AverageDrawdown"
      },
      {
        "text": "CalmarRatio",
        "link": "/Indicators/Indicator-CalmarRatio"
      },
      {
        "text": "ConditionalValueAtRisk",
        "link": "/Indicators/Indicator-ConditionalValueAtRisk"
      },
      {
        "text": "DrawdownDuration",
        "link": "/Indicators/Indicator-DrawdownDuration"
      },
      {
        "text": "GainLossRatio",
        "link": "/Indicators/Indicator-GainLossRatio"
      },
      {
        "text": "InformationRatio",
        "link": "/Indicators/Indicator-InformationRatio"
      },
      {
        "text": "KellyCriterion",
        "link": "/Indicators/Indicator-KellyCriterion"
      },
      {
        "text": "MaxDrawdown",
        "link": "/Indicators/Indicator-MaxDrawdown"
      },
      {
        "text": "OmegaRatio",
        "link": "/Indicators/Indicator-OmegaRatio"
      },
      {
        "text": "PainIndex",
        "link": "/Indicators/Indicator-PainIndex"
      },
      {
        "text": "ProfitFactor",
        "link": "/Indicators/Indicator-ProfitFactor"
      },
      {
        "text": "RecoveryFactor",
        "link": "/Indicators/Indicator-RecoveryFactor"
      },
      {
        "text": "SharpeRatio",
        "link": "/Indicators/Indicator-SharpeRatio"
      },
      {
        "text": "SortinoRatio",
        "link": "/Indicators/Indicator-SortinoRatio"
      },
      {
        "text": "TreynorRatio",
        "link": "/Indicators/Indicator-TreynorRatio"
      },
      {
        "text": "ValueAtRisk",
        "link": "/Indicators/Indicator-ValueAtRisk"
      },
      {
        "text": "Expectancy",
        "link": "/Indicators/Indicator-Expectancy"
      },
      {
        "text": "WinRate",
        "link": "/Indicators/Indicator-WinRate"
      }
    ]
  },
  {
    "text": "Microstructure",
    "collapsed": true,
    "items": [
      {
        "text": "CumulativeVolumeDelta",
        "link": "/Indicators/Indicator-CumulativeVolumeDelta"
      },
      {
        "text": "DepthSlope",
        "link": "/Indicators/Indicator-DepthSlope"
      },
      {
        "text": "EffectiveSpread",
        "link": "/Indicators/Indicator-EffectiveSpread"
      },
      {
        "text": "Footprint",
        "link": "/Indicators/Indicator-Footprint"
      },
      {
        "text": "KylesLambda",
        "link": "/Indicators/Indicator-KylesLambda"
      },
      {
        "text": "Microprice",
        "link": "/Indicators/Indicator-Microprice"
      },
      {
        "text": "OrderBookImbalanceFull",
        "link": "/Indicators/Indicator-OrderBookImbalanceFull"
      },
      {
        "text": "OrderBookImbalanceTop1",
        "link": "/Indicators/Indicator-OrderBookImbalanceTop1"
      },
      {
        "text": "OrderBookImbalanceTopN",
        "link": "/Indicators/Indicator-OrderBookImbalanceTopN"
      },
      {
        "text": "QuotedSpread",
        "link": "/Indicators/Indicator-QuotedSpread"
      },
      {
        "text": "RealizedSpread",
        "link": "/Indicators/Indicator-RealizedSpread"
      },
      {
        "text": "SignedVolume",
        "link": "/Indicators/Indicator-SignedVolume"
      },
      {
        "text": "TradeImbalance",
        "link": "/Indicators/Indicator-TradeImbalance"
      },
      {
        "text": "AmihudIlliquidity",
        "link": "/Indicators/Indicator-AmihudIlliquidity"
      },
      {
        "text": "OrderFlowImbalance",
        "link": "/Indicators/Indicator-OrderFlowImbalance"
      },
      {
        "text": "RollMeasure",
        "link": "/Indicators/Indicator-RollMeasure"
      },
      {
        "text": "Vpin",
        "link": "/Indicators/Indicator-Vpin"
      }
    ]
  },
  {
    "text": "Derivatives",
    "collapsed": true,
    "items": [
      {
        "text": "CalendarSpread",
        "link": "/Indicators/Indicator-CalendarSpread"
      },
      {
        "text": "FundingBasis",
        "link": "/Indicators/Indicator-FundingBasis"
      },
      {
        "text": "FundingRate",
        "link": "/Indicators/Indicator-FundingRate"
      },
      {
        "text": "FundingRateMean",
        "link": "/Indicators/Indicator-FundingRateMean"
      },
      {
        "text": "FundingRateZScore",
        "link": "/Indicators/Indicator-FundingRateZScore"
      },
      {
        "text": "LiquidationFeatures",
        "link": "/Indicators/Indicator-LiquidationFeatures"
      },
      {
        "text": "LongShortRatio",
        "link": "/Indicators/Indicator-LongShortRatio"
      },
      {
        "text": "OIPriceDivergence",
        "link": "/Indicators/Indicator-OIPriceDivergence"
      },
      {
        "text": "OIWeighted",
        "link": "/Indicators/Indicator-OIWeighted"
      },
      {
        "text": "OpenInterestDelta",
        "link": "/Indicators/Indicator-OpenInterestDelta"
      },
      {
        "text": "TakerBuySellRatio",
        "link": "/Indicators/Indicator-TakerBuySellRatio"
      },
      {
        "text": "TermStructureBasis",
        "link": "/Indicators/Indicator-TermStructureBasis"
      }
    ]
  },
  {
    "text": "Alt-Chart Bars",
    "collapsed": true,
    "items": [
      {
        "text": "KagiBars",
        "link": "/Indicators/Indicator-KagiBars"
      },
      {
        "text": "PointAndFigureBars",
        "link": "/Indicators/Indicator-PointAndFigureBars"
      },
      {
        "text": "RenkoBars",
        "link": "/Indicators/Indicator-RenkoBars"
      }
    ]
  },
  {
    "text": "Market Breadth",
    "collapsed": true,
    "items": [
      {
        "text": "AbsoluteBreadthIndex",
        "link": "/Indicators/Indicator-AbsoluteBreadthIndex"
      },
      {
        "text": "AdvanceDecline",
        "link": "/Indicators/Indicator-AdvanceDecline"
      },
      {
        "text": "AdvanceDeclineRatio",
        "link": "/Indicators/Indicator-AdvanceDeclineRatio"
      },
      {
        "text": "AdVolumeLine",
        "link": "/Indicators/Indicator-AdVolumeLine"
      },
      {
        "text": "BreadthThrust",
        "link": "/Indicators/Indicator-BreadthThrust"
      },
      {
        "text": "BullishPercentIndex",
        "link": "/Indicators/Indicator-BullishPercentIndex"
      },
      {
        "text": "CumulativeVolumeIndex",
        "link": "/Indicators/Indicator-CumulativeVolumeIndex"
      },
      {
        "text": "HighLowIndex",
        "link": "/Indicators/Indicator-HighLowIndex"
      },
      {
        "text": "McClellanOscillator",
        "link": "/Indicators/Indicator-McClellanOscillator"
      },
      {
        "text": "McClellanSummationIndex",
        "link": "/Indicators/Indicator-McClellanSummationIndex"
      },
      {
        "text": "NewHighsNewLows",
        "link": "/Indicators/Indicator-NewHighsNewLows"
      },
      {
        "text": "PercentAboveMa",
        "link": "/Indicators/Indicator-PercentAboveMa"
      },
      {
        "text": "TickIndex",
        "link": "/Indicators/Indicator-TickIndex"
      },
      {
        "text": "Trin",
        "link": "/Indicators/Indicator-Trin"
      },
      {
        "text": "UpDownVolumeRatio",
        "link": "/Indicators/Indicator-UpDownVolumeRatio"
      }
    ]
  },
  {
    "text": "Seasonality & Session",
    "collapsed": true,
    "items": [
      {
        "text": "AverageDailyRange",
        "link": "/Indicators/Indicator-AverageDailyRange"
      },
      {
        "text": "DayOfWeekProfile",
        "link": "/Indicators/Indicator-DayOfWeekProfile"
      },
      {
        "text": "IntradayVolatilityProfile",
        "link": "/Indicators/Indicator-IntradayVolatilityProfile"
      },
      {
        "text": "OvernightGap",
        "link": "/Indicators/Indicator-OvernightGap"
      },
      {
        "text": "OvernightIntradayReturn",
        "link": "/Indicators/Indicator-OvernightIntradayReturn"
      },
      {
        "text": "SeasonalZScore",
        "link": "/Indicators/Indicator-SeasonalZScore"
      },
      {
        "text": "SessionHighLow",
        "link": "/Indicators/Indicator-SessionHighLow"
      },
      {
        "text": "SessionRange",
        "link": "/Indicators/Indicator-SessionRange"
      },
      {
        "text": "SessionVwap",
        "link": "/Indicators/Indicator-SessionVwap"
      },
      {
        "text": "TimeOfDayReturnProfile",
        "link": "/Indicators/Indicator-TimeOfDayReturnProfile"
      },
      {
        "text": "TurnOfMonth",
        "link": "/Indicators/Indicator-TurnOfMonth"
      },
      {
        "text": "VolumeByTimeProfile",
        "link": "/Indicators/Indicator-VolumeByTimeProfile"
      }
    ]
  }
]
